-- Step 1: Clear all failed migration attempts
DELETE FROM "__EFMigrationsHistory" WHERE "MigrationId" LIKE '20260215%';

-- Step 2: Create Markets table
CREATE TABLE IF NOT EXISTS "Markets" (
    "Id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(200) NOT NULL,
    "Subdomain" character varying(100),
    "Description" character varying(500),
    "IsActive" boolean NOT NULL DEFAULT true,
    "ExpiresAt" timestamp without time zone,
    "CreatedAt" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_Markets_Subdomain" ON "Markets" ("Subdomain");

-- Step 3: Insert default market
INSERT INTO "Markets" ("Id", "Name", "Subdomain", "Description", "IsActive", "CreatedAt")
VALUES (1, 'Demo Market', 'demo', 'Default market for existing users', true, CURRENT_TIMESTAMP)
ON CONFLICT ("Id") DO NOTHING;

-- Step 4: Update existing users with default MarketId
UPDATE "Users" SET "MarketId" = 1 WHERE "MarketId" IS NULL OR "MarketId" = 0;
UPDATE "Products" SET "MarketId" = 1 WHERE "MarketId" IS NULL OR "MarketId" = 0;
UPDATE "Sales" SET "MarketId" = 1 WHERE "MarketId" IS NULL OR "MarketId" = 0;
UPDATE "Customers" SET "MarketId" = 1 WHERE "MarketId" IS NULL OR "MarketId" = 0;
UPDATE "Zakups" SET "MarketId" = 1 WHERE "MarketId" IS NULL OR "MarketId" = 0;
UPDATE "Debts" SET "MarketId" = 1 WHERE "MarketId" IS NULL OR "MarketId" = 0;
UPDATE "Payments" SET "MarketId" = 1 WHERE "MarketId" IS NULL OR "MarketId" = 0;
