CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260215234839_AddOwnerIdToMarket') THEN
    CREATE TABLE "AuditLogs" (
        "Id" uuid NOT NULL,
        "EntityType" character varying(100) NOT NULL,
        "EntityId" uuid NOT NULL,
        "Action" character varying(50) NOT NULL,
        "UserId" uuid NOT NULL,
        "Payload" text NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_AuditLogs" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260215234839_AddOwnerIdToMarket') THEN
    CREATE TABLE "CashRegisters" (
        "Id" uuid NOT NULL,
        "CurrentBalance" numeric(18,2) NOT NULL,
        "LastUpdated" timestamp with time zone NOT NULL,
        "LastWithdrawalId" uuid,
        CONSTRAINT "PK_CashRegisters" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260215234839_AddOwnerIdToMarket') THEN
    CREATE TABLE "CashWithdrawals" (
        "Id" uuid NOT NULL,
        "Amount" numeric(18,2) NOT NULL,
        "Comment" character varying(500) NOT NULL,
        "WithdrawalDate" timestamp with time zone NOT NULL,
        "UserId" uuid,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_CashWithdrawals" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260215234839_AddOwnerIdToMarket') THEN
    CREATE TABLE "Customers" (
        "Id" uuid NOT NULL,
        "Phone" character varying(20) NOT NULL,
        "FullName" character varying(200),
        "Comment" character varying(500),
        "IsDeleted" boolean NOT NULL,
        "MarketId" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Customers" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260215234839_AddOwnerIdToMarket') THEN
    CREATE TABLE "Debts" (
        "Id" uuid NOT NULL,
        "SaleId" uuid NOT NULL,
        "CustomerId" uuid NOT NULL,
        "TotalDebt" numeric(18,2) NOT NULL,
        "RemainingDebt" numeric(18,2) NOT NULL,
        "Status" integer NOT NULL,
        "MarketId" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Debts" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Debts_Customers_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES "Customers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260215234839_AddOwnerIdToMarket') THEN
    CREATE TABLE "Markets" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(200) NOT NULL,
        "Subdomain" character varying(100),
        "Description" character varying(500),
        "IsActive" boolean NOT NULL,
        "ExpiresAt" timestamp with time zone,
        "CreatedAt" timestamp with time zone NOT NULL,
        "OwnerId" uuid NOT NULL,
        CONSTRAINT "PK_Markets" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260215234839_AddOwnerIdToMarket') THEN
    CREATE TABLE "Users" (
        "Id" uuid NOT NULL,
        "FullName" character varying(200) NOT NULL,
        "Username" character varying(100) NOT NULL,
        "PasswordHash" text NOT NULL,
        "ProfileImage" text,
        "Role" integer NOT NULL,
        "Language" integer NOT NULL DEFAULT 0,
        "IsActive" boolean NOT NULL,
        "IsDeleted" boolean NOT NULL,
        "MarketId" integer,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Users" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Users_Markets_MarketId" FOREIGN KEY ("MarketId") REFERENCES "Markets" ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260215234839_AddOwnerIdToMarket') THEN
    CREATE TABLE "Products" (
        "Id" uuid NOT NULL,
        "Name" character varying(200) NOT NULL,
        "IsTemporary" boolean NOT NULL,
        "CreatedBySellerId" uuid,
        "IsDeleted" boolean NOT NULL,
        "CostPrice" numeric(18,2) NOT NULL,
        "SalePrice" numeric(18,2) NOT NULL,
        "MinSalePrice" numeric(18,2) NOT NULL,
        "Quantity" integer NOT NULL,
        "MinThreshold" integer NOT NULL,
        "MarketId" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Products" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Products_Markets_MarketId" FOREIGN KEY ("MarketId") REFERENCES "Markets" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Products_Users_CreatedBySellerId" FOREIGN KEY ("CreatedBySellerId") REFERENCES "Users" ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260215234839_AddOwnerIdToMarket') THEN
    CREATE TABLE "RefreshTokens" (
        "Id" uuid NOT NULL,
        "UserId" uuid NOT NULL,
        "Token" character varying(500) NOT NULL,
        "ExpiresAt" timestamp with time zone NOT NULL,
        "IsUsed" boolean NOT NULL,
        "IsRevoked" boolean NOT NULL,
        "RevokedAt" timestamp with time zone,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_RefreshTokens" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_RefreshTokens_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260215234839_AddOwnerIdToMarket') THEN
    CREATE TABLE "Sales" (
        "Id" uuid NOT NULL,
        "SellerId" uuid NOT NULL,
        "CustomerId" uuid,
        "Status" integer NOT NULL,
        "TotalAmount" numeric(18,2) NOT NULL,
        "PaidAmount" numeric(18,2) NOT NULL,
        "IsDeleted" boolean NOT NULL,
        "MarketId" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Sales" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Sales_Customers_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES "Customers" ("Id"),
        CONSTRAINT "FK_Sales_Markets_MarketId" FOREIGN KEY ("MarketId") REFERENCES "Markets" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Sales_Users_SellerId" FOREIGN KEY ("SellerId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260215234839_AddOwnerIdToMarket') THEN
    CREATE TABLE "Zakups" (
        "Id" uuid NOT NULL,
        "ProductId" uuid NOT NULL,
        "Quantity" numeric(18,3) NOT NULL,
        "CostPrice" numeric(18,2) NOT NULL,
        "CreatedByAdminId" uuid NOT NULL,
        "MarketId" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Zakups" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Zakups_Markets_MarketId" FOREIGN KEY ("MarketId") REFERENCES "Markets" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Zakups_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Zakups_Users_CreatedByAdminId" FOREIGN KEY ("CreatedByAdminId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260215234839_AddOwnerIdToMarket') THEN
    CREATE TABLE "Payments" (
        "Id" uuid NOT NULL,
        "SaleId" uuid NOT NULL,
        "PaymentType" integer NOT NULL,
        "Amount" numeric(18,2) NOT NULL,
        "MarketId" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Payments" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Payments_Markets_MarketId" FOREIGN KEY ("MarketId") REFERENCES "Markets" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Payments_Sales_SaleId" FOREIGN KEY ("SaleId") REFERENCES "Sales" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260215234839_AddOwnerIdToMarket') THEN
    CREATE TABLE "SaleItems" (
        "Id" uuid NOT NULL,
        "SaleId" uuid NOT NULL,
        "ProductId" uuid NOT NULL,
        "Quantity" integer NOT NULL,
        "CostPrice" numeric(18,2) NOT NULL,
        "SalePrice" numeric(18,2) NOT NULL,
        "Comment" character varying(500),
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_SaleItems" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_SaleItems_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_SaleItems_Sales_SaleId" FOREIGN KEY ("SaleId") REFERENCES "Sales" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260215234839_AddOwnerIdToMarket') THEN
    CREATE INDEX "IX_AuditLog_Entity_CreatedAt" ON "AuditLogs" ("EntityType", "EntityId", "CreatedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260215234839_AddOwnerIdToMarket') THEN
    CREATE INDEX "IX_AuditLog_User_CreatedAt" ON "AuditLogs" ("UserId", "CreatedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260215234839_AddOwnerIdToMarket') THEN
    CREATE INDEX "IX_CashRegisters_LastUpdated" ON "CashRegisters" ("LastUpdated");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260215234839_AddOwnerIdToMarket') THEN
    CREATE INDEX "IX_CashRegisters_LastWithdrawalId" ON "CashRegisters" ("LastWithdrawalId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260215234839_AddOwnerIdToMarket') THEN
    CREATE INDEX "IX_CashWithdrawals_UserId" ON "CashWithdrawals" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260215234839_AddOwnerIdToMarket') THEN
    CREATE INDEX "IX_CashWithdrawals_WithdrawalDate" ON "CashWithdrawals" ("WithdrawalDate");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260215234839_AddOwnerIdToMarket') THEN
    CREATE INDEX "IX_Customers_MarketId" ON "Customers" ("MarketId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260215234839_AddOwnerIdToMarket') THEN
    CREATE UNIQUE INDEX "IX_Customers_Phone" ON "Customers" ("Phone");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260215234839_AddOwnerIdToMarket') THEN
    CREATE INDEX "IX_Debt_Customer_Status" ON "Debts" ("CustomerId", "Status");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260215234839_AddOwnerIdToMarket') THEN
    CREATE INDEX "IX_Debts_MarketId" ON "Debts" ("MarketId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260215234839_AddOwnerIdToMarket') THEN
    CREATE UNIQUE INDEX "IX_Debts_SaleId" ON "Debts" ("SaleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260215234839_AddOwnerIdToMarket') THEN
    CREATE UNIQUE INDEX "IX_Markets_Name" ON "Markets" ("Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260215234839_AddOwnerIdToMarket') THEN
    CREATE INDEX "IX_Markets_OwnerId" ON "Markets" ("OwnerId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260215234839_AddOwnerIdToMarket') THEN
    CREATE UNIQUE INDEX "IX_Markets_Subdomain" ON "Markets" ("Subdomain");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260215234839_AddOwnerIdToMarket') THEN
    CREATE INDEX "IX_Payment_SaleId" ON "Payments" ("SaleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260215234839_AddOwnerIdToMarket') THEN
    CREATE INDEX "IX_Payments_MarketId" ON "Payments" ("MarketId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260215234839_AddOwnerIdToMarket') THEN
    CREATE INDEX "IX_Products_CreatedBySellerId" ON "Products" ("CreatedBySellerId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260215234839_AddOwnerIdToMarket') THEN
    CREATE INDEX "IX_Products_MarketId" ON "Products" ("MarketId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260215234839_AddOwnerIdToMarket') THEN
    CREATE INDEX "IX_RefreshToken_Token" ON "RefreshTokens" ("Token");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260215234839_AddOwnerIdToMarket') THEN
    CREATE INDEX "IX_RefreshToken_User_ExpiresAt" ON "RefreshTokens" ("UserId", "ExpiresAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260215234839_AddOwnerIdToMarket') THEN
    CREATE INDEX "IX_SaleItem_Sale_Product" ON "SaleItems" ("SaleId", "ProductId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260215234839_AddOwnerIdToMarket') THEN
    CREATE INDEX "IX_SaleItems_ProductId" ON "SaleItems" ("ProductId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260215234839_AddOwnerIdToMarket') THEN
    CREATE INDEX "IX_Sale_CustomerId" ON "Sales" ("CustomerId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260215234839_AddOwnerIdToMarket') THEN
    CREATE INDEX "IX_Sale_Seller_Status" ON "Sales" ("SellerId", "Status");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260215234839_AddOwnerIdToMarket') THEN
    CREATE INDEX "IX_Sale_Status_CreatedAt" ON "Sales" ("Status", "CreatedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260215234839_AddOwnerIdToMarket') THEN
    CREATE INDEX "IX_Sales_MarketId" ON "Sales" ("MarketId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260215234839_AddOwnerIdToMarket') THEN
    CREATE INDEX "IX_Users_MarketId" ON "Users" ("MarketId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260215234839_AddOwnerIdToMarket') THEN
    CREATE UNIQUE INDEX "IX_Users_Username" ON "Users" ("Username");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260215234839_AddOwnerIdToMarket') THEN
    CREATE INDEX "IX_Zakups_CreatedByAdminId" ON "Zakups" ("CreatedByAdminId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260215234839_AddOwnerIdToMarket') THEN
    CREATE INDEX "IX_Zakups_MarketId" ON "Zakups" ("MarketId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260215234839_AddOwnerIdToMarket') THEN
    CREATE INDEX "IX_Zakups_ProductId" ON "Zakups" ("ProductId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260215234839_AddOwnerIdToMarket') THEN
    ALTER TABLE "AuditLogs" ADD CONSTRAINT "FK_AuditLogs_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260215234839_AddOwnerIdToMarket') THEN
    ALTER TABLE "CashRegisters" ADD CONSTRAINT "FK_CashRegisters_CashWithdrawals_LastWithdrawalId" FOREIGN KEY ("LastWithdrawalId") REFERENCES "CashWithdrawals" ("Id");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260215234839_AddOwnerIdToMarket') THEN
    ALTER TABLE "CashWithdrawals" ADD CONSTRAINT "FK_CashWithdrawals_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260215234839_AddOwnerIdToMarket') THEN
    ALTER TABLE "Customers" ADD CONSTRAINT "FK_Customers_Markets_MarketId" FOREIGN KEY ("MarketId") REFERENCES "Markets" ("Id") ON DELETE CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260215234839_AddOwnerIdToMarket') THEN
    ALTER TABLE "Debts" ADD CONSTRAINT "FK_Debts_Markets_MarketId" FOREIGN KEY ("MarketId") REFERENCES "Markets" ("Id") ON DELETE CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260215234839_AddOwnerIdToMarket') THEN
    ALTER TABLE "Debts" ADD CONSTRAINT "FK_Debts_Sales_SaleId" FOREIGN KEY ("SaleId") REFERENCES "Sales" ("Id") ON DELETE CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260215234839_AddOwnerIdToMarket') THEN
    ALTER TABLE "Markets" ADD CONSTRAINT "FK_Markets_Users_OwnerId" FOREIGN KEY ("OwnerId") REFERENCES "Users" ("Id") ON DELETE CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260215234839_AddOwnerIdToMarket') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260215234839_AddOwnerIdToMarket', '9.0.4');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260216145706_AddDebtAuditLog') THEN
    CREATE TABLE "DebtAuditLogs" (
        "Id" uuid NOT NULL,
        "SaleId" uuid NOT NULL,
        "SaleItemId" uuid NOT NULL,
        "OldPrice" numeric(18,2) NOT NULL,
        "NewPrice" numeric(18,2) NOT NULL,
        "ChangedByUserId" uuid NOT NULL,
        "Comment" character varying(500) NOT NULL,
        "MarketId" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_DebtAuditLogs" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_DebtAuditLogs_Markets_MarketId" FOREIGN KEY ("MarketId") REFERENCES "Markets" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_DebtAuditLogs_SaleItems_SaleItemId" FOREIGN KEY ("SaleItemId") REFERENCES "SaleItems" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_DebtAuditLogs_Sales_SaleId" FOREIGN KEY ("SaleId") REFERENCES "Sales" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_DebtAuditLogs_Users_ChangedByUserId" FOREIGN KEY ("ChangedByUserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260216145706_AddDebtAuditLog') THEN
    CREATE INDEX "IX_DebtAuditLog_ChangedBy" ON "DebtAuditLogs" ("ChangedByUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260216145706_AddDebtAuditLog') THEN
    CREATE INDEX "IX_DebtAuditLog_Sale_CreatedAt" ON "DebtAuditLogs" ("SaleId", "CreatedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260216145706_AddDebtAuditLog') THEN
    CREATE INDEX "IX_DebtAuditLog_SaleItem_CreatedAt" ON "DebtAuditLogs" ("SaleItemId", "CreatedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260216145706_AddDebtAuditLog') THEN
    CREATE INDEX "IX_DebtAuditLogs_MarketId" ON "DebtAuditLogs" ("MarketId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260216145706_AddDebtAuditLog') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260216145706_AddDebtAuditLog', '9.0.4');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260217145805_AddWithdrawTypeToCashWithdrawal') THEN
    ALTER TABLE "CashWithdrawals" ADD "WithdrawType" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260217145805_AddWithdrawTypeToCashWithdrawal') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260217145805_AddWithdrawTypeToCashWithdrawal', '9.0.4');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260219135549_MarketMigration5') THEN
    ALTER TABLE "AuditLogs" DROP CONSTRAINT "FK_AuditLogs_Users_UserId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260219135549_MarketMigration5') THEN
    ALTER TABLE "DebtAuditLogs" DROP CONSTRAINT "FK_DebtAuditLogs_SaleItems_SaleItemId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260219135549_MarketMigration5') THEN
    ALTER TABLE "DebtAuditLogs" DROP CONSTRAINT "FK_DebtAuditLogs_Sales_SaleId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260219135549_MarketMigration5') THEN
    ALTER TABLE "DebtAuditLogs" DROP CONSTRAINT "FK_DebtAuditLogs_Users_ChangedByUserId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260219135549_MarketMigration5') THEN
    ALTER TABLE "Debts" DROP CONSTRAINT "FK_Debts_Customers_CustomerId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260219135549_MarketMigration5') THEN
    ALTER TABLE "SaleItems" DROP CONSTRAINT "FK_SaleItems_Products_ProductId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260219135549_MarketMigration5') THEN
    ALTER TABLE "Sales" DROP CONSTRAINT "FK_Sales_Customers_CustomerId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260219135549_MarketMigration5') THEN
    ALTER TABLE "Sales" DROP CONSTRAINT "FK_Sales_Users_SellerId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260219135549_MarketMigration5') THEN
    ALTER TABLE "Zakups" DROP CONSTRAINT "FK_Zakups_Products_ProductId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260219135549_MarketMigration5') THEN
    ALTER TABLE "Zakups" DROP CONSTRAINT "FK_Zakups_Users_CreatedByAdminId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260219135549_MarketMigration5') THEN
    ALTER TABLE "AuditLogs" ADD CONSTRAINT "FK_AuditLogs_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260219135549_MarketMigration5') THEN
    ALTER TABLE "DebtAuditLogs" ADD CONSTRAINT "FK_DebtAuditLogs_SaleItems_SaleItemId" FOREIGN KEY ("SaleItemId") REFERENCES "SaleItems" ("Id") ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260219135549_MarketMigration5') THEN
    ALTER TABLE "DebtAuditLogs" ADD CONSTRAINT "FK_DebtAuditLogs_Sales_SaleId" FOREIGN KEY ("SaleId") REFERENCES "Sales" ("Id") ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260219135549_MarketMigration5') THEN
    ALTER TABLE "DebtAuditLogs" ADD CONSTRAINT "FK_DebtAuditLogs_Users_ChangedByUserId" FOREIGN KEY ("ChangedByUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260219135549_MarketMigration5') THEN
    ALTER TABLE "Debts" ADD CONSTRAINT "FK_Debts_Customers_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES "Customers" ("Id") ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260219135549_MarketMigration5') THEN
    ALTER TABLE "SaleItems" ADD CONSTRAINT "FK_SaleItems_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260219135549_MarketMigration5') THEN
    ALTER TABLE "Sales" ADD CONSTRAINT "FK_Sales_Customers_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES "Customers" ("Id") ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260219135549_MarketMigration5') THEN
    ALTER TABLE "Sales" ADD CONSTRAINT "FK_Sales_Users_SellerId" FOREIGN KEY ("SellerId") REFERENCES "Users" ("Id") ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260219135549_MarketMigration5') THEN
    ALTER TABLE "Zakups" ADD CONSTRAINT "FK_Zakups_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260219135549_MarketMigration5') THEN
    ALTER TABLE "Zakups" ADD CONSTRAINT "FK_Zakups_Users_CreatedByAdminId" FOREIGN KEY ("CreatedByAdminId") REFERENCES "Users" ("Id") ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260219135549_MarketMigration5') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260219135549_MarketMigration5', '9.0.4');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260219163103_Marketmigration91') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260219163103_Marketmigration91', '9.0.4');
    END IF;
END $EF$;
COMMIT;

